# Generated by Django 5.0.6 on 2024-06-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='Cost_per_Item',
            new_name='cost_per_item',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='Last_Sales_Date',
            new_name='last_sales_date',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='Quantity_Sold',
            new_name='quantity_sold',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='Sales',
            new_name='sales',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='Stock_Date',
            new_name='stock_Date',
        ),
    ]
