# Generated by Django 5.0.6 on 2024-06-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_rename_cost_per_item_inventory_cost_per_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='Quantity_in_Stock',
            new_name='quantity_in_stock',
        ),
    ]
